module.exports = {
  products: [
    {
      _id: "1",
      name: "Full Sleeve Shirt",
      category: "Shirts",
      image: "/images/product-1.jpg",
      price: 60,
      brand: "killshot",
      rating: 4.5,
      numReviews: 10,
      countInStock: 6,
    },
    {
      _id: "2",
      name: "Full Sleeve Shirt 2",
      category: "Shirts",
      image: "/images/product-2.jpg",
      price: 66,
      brand: "killshot",
      rating: 4.7,
      numReviews: 17,
      countInStock: 10,
    },
    {
      _id: "3",
      name: "Polo T-shirt",
      category: "T-Shirts",
      image: "/images/product-3.jpg",
      price: 39,
      brand: "killshot",
      rating: 4.5,
      numReviews: 10,
      countInStock: 6,
    },
    {
      _id: "4",
      name: "Polo T-shirt 2",
      category: "T-Shirts",
      image: "/images/product-4.jpg",
      price: 50,
      brand: "killshot",
      rating: 4.9,
      numReviews: 20,
      countInStock: 3,
    },
    {
      _id: "5",
      name: "Chinos",
      category: "Pants",
      image: "/images/product-5.jpg",
      price: 47,
      brand: "killshot",
      rating: 4.5,
      numReviews: 10,
      countInStock: 6,
    },
    {
      _id: "6",
      name: "Checked Trouser",
      category: "Pants",
      image: "/images/product-6.jpg",
      price: 60,
      brand: "killshot",
      rating: 4.5,
      numReviews: 10,
      countInStock: 6,
    },
  ],
};
